### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShotDead7297** [JaxkDev/Bounty#1]
whats this plugin about ?

**Comment by JaxkDev** [comment]
This plugin is at the moment privately used on a server I co own but I do have plans to release to public soon,
The plugin is Bounty:
Place a bounty on a user /bounty new <player name> <price>
And when you kill the player the specified price is given to the killer.
EconomyAPI is required.

**Comment by ShotDead7297** [comment]
so when will that be released i will so use that

**Comment by JaxkDev** [comment]
Just waiting to hear back from the testers if it’s good, today if not probably in 2-3 working days

**Comment by ShotDead7297** [comment]
well u need to fix this plugin i placed a bounty on someone and i killed them and i didnt get the money

**Comment by JaxkDev** [comment]
You don’t have the up to date private version.

**Comment by ShotDead7297** [comment]
hi its been 3 days when does it come out im asking because i just love your plugins

**Comment by JaxkDev** [comment]
At the moment its fully ready, I’ll modify it for public and get a phar uploaded to the release section today.

**Comment by JaxkDev** [comment]
Released over in the releases section of this github project there may be a few issues if so please re create a issue with full details !

**Comment by ShotDead7297** [comment]
ok thanks do u have a link where i can get it at ?

**Comment by JaxkDev** [comment]
https://github.com/jackthehack21/Bounty/releases
