### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by eliassaliba12** [JaxkDev/Bounty#12]
Add an option to auto add a bounty on a player when he kill another player

**Comment by JaxkDev** [comment]
Can i get more information like what sort of behaviour you would expect, eg how much per person and specific scenarios etc.

**Comment by eliassaliba12** [comment]
Automaticly after a player killing someone a small amount if money is putted on him as bounty this amount should be configurable and add optiom on where to activate this feature like you enter the world names that you want this feature active in and add in configue max amount if kills be4 stopping adding to his bounty bit when the player is finally killed if he start killing ither players again the feature reactivate

**Comment by eliassaliba12** [comment]
Automaticly after a player killing someone a small amount if money is putted on him as bounty this amount should be configurable and add optiom on where to activate this feature like you enter the world names that you want this feature active in and add in configue max amount if kills be4 stopping adding to his bounty bit when the player is finally killed if he start killing ither players again the feature reactivate

**Comment by BroCrows** [comment]
I like this idea

**Comment by JaxkDev** [comment]
Don't fully understand, does the bounty get rewarded and a new bounty of the amount gained put on the killer ?

**Comment by JaxkDev** [comment]
Not enough information to work with.
