### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SuperAdam47** [JaxkDev/Bounty#14]
Add top bounty
/bounty top (list)
/bounty top create (creates top bounty names in floatingtexts)

**Comment by JaxkDev** [comment]
there is both `/bounty list`
and `/bounty leaderboard`

**Comment by SuperAdam47** [comment]
in floatingtexts ?

**Comment by JaxkDev** [comment]
Floating text lb was stripped out of core.
<https://github.com/JaxkDev/Bounty/releases/tag/1.1.2>

**Comment by SuperAdam47** [comment]
When I kill the enemy with a snowball, he won't give me the money.

**Comment by SuperAdam47** [comment]
fix please?

**Comment by JaxkDev** [comment]
Thats a entire different issue, make a new one.
