### ISSUE TITLE
Suppor UI

### ISSUE THREAD

**Issue by Wolfkid200444** [JaxkDev/Bounty#3]
Do3s the plugin support UI?

**Comment by JaxkDev** [comment]
Not now, but it will definitely support UI in the near future.

**Comment by JaxkDev** [comment]
Where would you like to see UI implemented ?

**Comment by Wolfkid200444** [comment]
When u do /bounty and u can choose different options

**Comment by JaxkDev** [comment]
Hmm very interesting I will definitely consider this however before any UI I plan to add config and better back end code.

**Comment by Wolfkid200444** [comment]
Ok
