### ISSUE TITLE
Current bounties

### ISSUE THREAD

**Issue by isoz** [JaxkDev/Bounty#4]
Needs a list to check current active bounties, either by command or floating text.

**Comment by JaxkDev** [comment]
This is planned to be /bounty list <page>
In near future, but as I’ve seen over 50 people view this in the last 2hours I’ll definitely be considering properly updating this and adding new features.

**Comment by isoz** [comment]
A floating text option would be great for it to be displayed at spawn for
everyone to see. Thank you.

**Comment by JaxkDev** [comment]
With that option it may not be suitable for everyone else who uses this so the command will definitely be released however the floating text I can’t garuntee I may add it or not I will update this issue later in the week, any other issues please re create one, thanks !
