### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ShotDead7297** [JaxkDev/Bounty#5]
Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'Bounty v1.0.2': Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager() on Jack\Bounty\Main
25.08 16:29:31 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\event\entity\EntityDamageEvent::getDamager()" (EXCEPTION) in "Bounty-master/src/Jack/Bounty/Main" at line 138
25.08 16:29:31 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): Jack\Bounty\Main->onDeath(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(Jack\Bounty\Main object, pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(752): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #3 src/pocketmine/Player(3619): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerDeathEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #4 src/pocketmine/entity/Living(594): pocketmine\Player->onDeath()
25.08 16:29:31 [Server] Server thread/DEBUG #5 src/pocketmine/Player(3497): pocketmine\entity\Living->kill()
25.08 16:29:31 [Server] Server thread/DEBUG #6 src/pocketmine/entity/Entity(952): pocketmine\Player->kill()
25.08 16:29:31 [Server] Server thread/DEBUG #7 src/pocketmine/entity/Living(129): pocketmine\entity\Entity->setHealth(double 0)
25.08 16:29:31 [Server] Server thread/DEBUG #8 src/pocketmine/entity/Entity(898): pocketmine\entity\Living->setHealth(double 0)
25.08 16:29:31 [Server] Server thread/DEBUG #9 src/pocketmine/entity/Living(532): pocketmine\entity\Entity->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #10 src/pocketmine/Player(3704): pocketmine\entity\Living->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #11 src/pocketmine/entity/Entity(1014): pocketmine\Player->attack(pocketmine\event\entity\EntityDamageEvent object)
25.08 16:29:31 [Server] Server thread/DEBUG #12 src/pocketmine/entity/Living(630): pocketmine\entity\Entity->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #13 src/pocketmine/entity/Human(633): pocketmine\entity\Living->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #14 src/pocketmine/Player(1704): pocketmine\entity\Human->entityBaseTick(integer 1)
25.08 16:29:31 [Server] Server thread/DEBUG #15 src/pocketmine/level/Level(743): pocketmine\Player->onUpdate(integer 7491)
25.08 16:29:31 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2359): pocketmine\level\Level->doTick(integer 7491)
25.08 16:29:31 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2516): pocketmine\Server->checkTickUpdates(integer 7491, double 1535214571.0261)
25.08 16:29:31 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2258): pocketmine\Server->tick()
25.08 16:29:31 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2132): pocketmine\Server->tickProcessor()
25.08 16:29:31 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1713): pocketmine\Server->start()
25.08 16:29:31 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
25.08 16:29:31 [Server] Server thread/DEBUG #22 /pmmp_1269_1.5.0.phar(1): require(string phar:///pmmp_1269_1.5.0.phar/src/pocketmine/PocketMine.php)

**Comment by JaxkDev** [comment]
what version of Pocketmine-Mp @cujowilliams123

**Comment by ShotDead7297** [comment]
3.1.1

**Comment by JaxkDev** [comment]
Ah yes I just remembered this is known, but to remove that error makes the bounty reward not work, I will try and look into it today but very busy.

**Comment by ShotDead7297** [comment]
ok thanks so much

**Comment by iZeaoGamer** [comment]
I think there's a fix out already for this above ^
On my PR. The PR is however, outdated, and the latest comment / commit should resolve everything this and other people are experiencing.

**Comment by JaxkDev** [comment]
Latest commit fixes this issue.
