### ISSUE TITLE
"You claimed bounty" message is sent to everyone

### ISSUE THREAD

**Issue by KadTheHunter** [JaxkDev/Bounty#8]
On my server, whenever someone kills a player with a bounty on their head, the message of "Nice one, you claimed the bounty on <player> worth $<amount>" is sent to everyone on the server."
Example:
I place a bounty on manmadeofgummy worth $10
XxWolfie14xX kills manmadeofgummy, and receives the $10 as a reward, but the "Nice one, you claimed the bounty on manmadeofgummy worth $10" is sent to everyone on the server, not just XxWolfie14xX.

**Comment by JaxkDev** [comment]
Thanks for the report, no need to replicate I can see the problem in the code.
For now use the success message as the broadcast one.

Will be fixed in next patch update.

**Comment by JaxkDev** [comment]
Please test latest commit e558d19 if it does not work please comment here.
