### ISSUE TITLE
Multiple Bounty’s Suggestion

### ISSUE THREAD

**Issue by mikeygio10** [JaxkDev/Bounty#9]
Make is so multiple players can do /bounty add ( amount ) not just one player

**Comment by mikeygio10** [comment]
What I mean is I can add multiple bounty’s to one players
Example 
Bill did /bounty joe 1000$

Then chuck did /bounty joe 1000$ 

But it will not let you do that only 1 player can bounty someone

**Comment by KadTheHunter** [comment]
I think this would be awesome as well. Then it would just stack the Bounties into 1 (and therefore technically making it so instead of chuck adding a second bounty on joe, he's just raising the bounty that bill placed)

**Comment by mikeygio10** [comment]
Forgot the command is /bounty new 
I think it should be /bounty add too

**Comment by JaxkDev** [comment]
Was discussed ages ago and planned for 1.2.0
Will leave the issue here for further updates.

**Comment by JaxkDev** [comment]
v1.1.0 has multiple bounty support.
<https://github.com/jackthehack21/Bounty/releases/tag/1.1.0>
